Package according modern guidelines
closes https://github.com/BramVanroy/spacy_conll/issues/31

Project repackaged accoding modern Python packaging guidelines:
https://packaging.python.org/en/latest/

The main reason for repackaging is that previously it was not possible to
build/install package in virtualenv when spacy was not installed in
system environment, because `setup.py` imported all project modules
indirectly through importing `__init__.py`:
```
$ python3 -m venv .venv
$ source .venv/bin/activate
$ pip install .
Processing /home/rominf/dev/spacy_conll
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-tbqma0n0/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-tbqma0n0/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-tbqma0n0/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-tbqma0n0/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 4, in <module>
        File "/home/rominf/dev/spacy_conll/spacy_conll/__init__.py", line 3, in <module>
          from .formatter import ConllFormatter
        File "/home/rominf/dev/spacy_conll/spacy_conll/formatter.py", line 5, in <module>
          from spacy.language import Language
      ModuleNotFoundError: No module named 'spacy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

Also, switch to dynamic versioning based on git tags, see:
https://github.com/ofek/hatch-vcs